# Generated by Django 3.2.13 on 2022-10-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.TextField(choices=[('2', '국내영화'), ('3', '해외영화')], default='2'),
        ),
    ]
